# Generated by Django 5.0.7 on 2024-07-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='players',
        ),
        migrations.AddField(
            model_name='agent',
            name='players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='catalog.player'),
        ),
    ]
