# Generated by Django 5.0.7 on 2024-07-18 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_agent_players_agent_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'agent', 'verbose_name_plural': 'agents'},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='players',
        ),
        migrations.RemoveField(
            model_name='club',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
